[package]
name = "project-euler"
version = "0.1.0"
authors = ["steabert <steabert@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "euler"
path = "src/problem_007.rs"
